name: Run ESLint CI
on:
  push:
    branches: 
      - 'eslint-ci'
    tags: [v*]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install all modules
        run: npm install

      - name: Execute Eslint
        run: npm run lint --fix
